project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Yifei Yang"
  site-url: https://yifeiyang05.github.io
  favicon: images/site_logo.png
  repo-url: https://yeerf.github.io/YEERF/yifeiyang05.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      © 2025 Yifei Yang
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细